name: "Code Style Review"

on:
  pull_request:
    branches:
      - "master"
    paths-ignore:
      - "doc/**"
      - "**.md"

jobs:
  lint:
    runs-on: "ubuntu-latest"

    steps:
#      - name: "Checkout"
#        uses: actions/checkout@v4

      - name: "Set up Ruby"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

